# Generated by Django 2.1.2 on 2020-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('gh', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=8)),
                ('xb', models.CharField(max_length=4)),
                ('pwd', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('xh', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=8)),
                ('xb', models.CharField(max_length=4)),
                ('csrq', models.DateField(max_length=12)),
                ('jg', models.CharField(max_length=12)),
                ('sjhm', models.CharField(max_length=8)),
                ('yxh', models.CharField(max_length=8)),
                ('pwd', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('gh', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('xm', models.CharField(max_length=8)),
                ('xb', models.CharField(max_length=4)),
                ('csrq', models.DateField(max_length=12)),
                ('xl', models.CharField(max_length=12)),
                ('jbgz', models.CharField(max_length=8)),
                ('yxh', models.CharField(max_length=8)),
                ('pwd', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=2)),
                ('pswd', models.CharField(max_length=8)),
            ],
        ),
    ]
