# Generated by Django 2.1.2 on 2020-06-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('kh', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('km', models.CharField(max_length=16)),
                ('xf', models.IntegerField()),
                ('xs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('yxh', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('mc', models.CharField(max_length=16)),
                ('dz', models.CharField(max_length=25)),
                ('lxdh', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='e_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=20)),
                ('pscj', models.IntegerField()),
                ('kscj', models.IntegerField()),
                ('zpcj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='open_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=20)),
                ('sksj', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='yxh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='yxh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department'),
        ),
        migrations.AddField(
            model_name='open_course',
            name='gh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.teacher'),
        ),
        migrations.AddField(
            model_name='open_course',
            name='kh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.course'),
        ),
        migrations.AddField(
            model_name='e_table',
            name='gh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.teacher'),
        ),
        migrations.AddField(
            model_name='e_table',
            name='kh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.course'),
        ),
        migrations.AddField(
            model_name='e_table',
            name='xh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='yxh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department'),
        ),
    ]
