# Generated by Django 2.1.2 on 2020-06-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200613_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=20)),
                ('bsrq', models.DateField(max_length=12)),
                ('zk', models.CharField(max_length=10)),
                ('tw', models.CharField(max_length=5)),
                ('xh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student')),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
            ],
        ),
        migrations.CreateModel(
            name='tea_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=20)),
                ('bsrq', models.DateField(max_length=12)),
                ('zk', models.CharField(max_length=10)),
                ('tw', models.CharField(max_length=5)),
                ('xh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.teacher')),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
            ],
        ),
    ]
