# Generated by Django 2.1.2 on 2020-06-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_stu_status_tea_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea_status',
            name='xh',
        ),
        migrations.RemoveField(
            model_name='tea_status',
            name='yxh',
        ),
        migrations.DeleteModel(
            name='tea_status',
        ),
    ]
