# Generated by Django 2.1.2 on 2020-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_tea_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='term_status',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='e_table',
            name='xq',
        ),
        migrations.RemoveField(
            model_name='open_course',
            name='xq',
        ),
    ]
