# Generated by Django 2.1.2 on 2020-07-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200724_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_table',
            name='xq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.term_status'),
        ),
        migrations.AddField(
            model_name='open_course',
            name='xq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.term_status'),
        ),
    ]
