# Generated by Django 3.0.7 on 2020-07-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200724_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term_status',
            old_name='name',
            new_name='xq',
        ),
    ]
