# Generated by Django 3.0.7 on 2020-08-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200726_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term_status',
            old_name='xq',
            new_name='name',
        ),
    ]
